過去のニュースの追加
ArchLinuxJP/archweb-jp pull request #36
Opened 2020-03-19 15:34 UTC by ny-a

過去のニュースですが、

- https://www.archlinux.org/news/install-media-20120715-released/
- https://www.archlinux.org/news/final-sysvinit-deprecation-warning/

の2点について、https://wiki.archlinux.jp/index.php/Arch_Linux に追加されているものの翻訳されていないため、可能であれば追加したいです。

"install-media-20120715-released" の方については、リンク切れ等ありますが8年前のもののため特に修正せずそのままにしてあります。

2020-03-23 15:14 UTC, kusakata requested changes

2020-03-23 15:14 UTC, kusakata commented on views/news/index.sql
> +	)
閉じ括弧の後ろにカンマを追加してください

2020-03-23 15:14 UTC, kusakata commented on views/news/index.sql
> +	)
こちらもカンマを追加してください

2020-03-23 15:18 UTC, ny-a commented on views/news/index.sql
> +	)
失礼しました、修正しました。

2020-03-23 15:19 UTC, ny-a commented on views/news/index.sql
> +	)
こちらも修正しました。

2020-03-25 00:42 UTC, kusakata approved these changes
ありがとうございます

2020-04-06 00:37 UTC, merged